[package]
name = "hello-rust"
version = "0.6.9"
authors = ["Alex Todoran <alex-tdrn@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = "0.40.0"